[server.http]
enabled = true
addr = "0.0.0.0:8050"
max_body_size = 2097152

[server.grpc]
enabled = false
addr = "0.0.0.0:8051"


[solidity]
enabled = true
compilers_dir = "/tmp/solidity-compilers"
refresh_versions_schedule = "0 0 * * * * *"

# For list fetcher (commented out):
# [solidity.fetcher]
# list = { list_url = "https://solc-bin.ethereum.org/macosx-amd64/list.json" }

# For S3 fetcher:
[solidity.fetcher]
s3 = { region = "us-east-1", bucket = "solidity-public" }

[vyper]
enabled = false
compilers_dir = "/tmp/vyper-compilers"
refresh_versions_schedule = "0 0 * * * * *"

[vyper.fetcher.list]
list_url = "https://raw.githubusercontent.com/blockscout/solc-bin/main/vyper.list.json"
# list_url = "https://raw.githubusercontent.com/blockscout/solc-bin/main/vyper.macos.list.json"

[sourcify]
enabled = true
api_url = "https://sourcify.dev/server/"
verification_attempts = 3
request_timeout = 15

[metrics]
enabled = false
addr = "0.0.0.0:6060"
route = "/metrics"

[jaeger]
enabled = false
agent_endpoint = "localhost:6831"

[compilers]
# if omitted, number of CPU cores would be used
max_threads = 8

# [extensions.solidity.sig_provider]
# url = "http://127.0.0.1:8051/"

# [extensions.vyper.sig_provider]
# url = "http://127.0.0.1:8051/"

# [extensions.sourcify.sig_provider]
# url = "http://127.0.0.1:8051/"
